2024-06-22 14:45:54,773 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-06-22 14:45:54,779 - discord.client - INFO - logging in using static token
2024-06-22 14:45:56,396 - arp_scan - ERROR - ARP scan failed: Interface: wlan0, type: EN10MB, MAC: d8:3a:dd:36:a1:e0, IPv4: 192.168.0.12
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.0.1	86:9f:08:fb:5d:b3	(Unknown: locally administered)

2024-06-22 14:45:59,108 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 40bc4e078ce8e7824ea47eeee923f465).
2024-06-22 14:46:22,704 - arp_scan - ERROR - ARP scan failed: Interface: wlan0, type: EN10MB, MAC: d8:3a:dd:36:a1:e0, IPv4: 192.168.0.12
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

2024-06-22 14:46:33,840 - arp_scan - ERROR - ARP scan failed: Interface: wlan0, type: EN10MB, MAC: d8:3a:dd:36:a1:e0, IPv4: 192.168.0.12
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

2024-06-22 14:46:45,132 - arp_scan - ERROR - ARP scan failed: Interface: wlan0, type: EN10MB, MAC: d8:3a:dd:36:a1:e0, IPv4: 192.168.0.12
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
192.168.0.4	d8:3a:dd:3f:a8:3d	Raspberry Pi Trading Ltd
192.168.0.6	c2:44:1a:25:23:20	(Unknown: locally administered)
192.168.0.4	d8:3a:dd:3f:a8:3d	Raspberry Pi Trading Ltd (DUP: 2)
192.168.0.4	d8:3a:dd:3f:a8:3d	Raspberry Pi Trading Ltd (DUP: 3)

2024-06-22 14:51:05,736 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-06-22 14:51:05,744 - discord.client - INFO - logging in using static token
2024-06-22 14:51:05,892 - __main__ - ERROR - Attempt 1: An error occurred during bot setup or execution: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
2024-06-22 14:51:15,895 - discord.client - INFO - logging in using static token
2024-06-22 14:51:15,897 - __main__ - ERROR - Attempt 2: An error occurred during bot setup or execution: Session is closed
2024-06-22 14:51:25,904 - discord.client - INFO - logging in using static token
2024-06-22 14:51:25,905 - __main__ - ERROR - Attempt 3: An error occurred during bot setup or execution: Session is closed
2024-06-22 14:51:35,908 - discord.client - INFO - logging in using static token
2024-06-22 14:51:35,909 - __main__ - ERROR - Attempt 4: An error occurred during bot setup or execution: Session is closed
2024-06-22 14:51:45,911 - discord.client - INFO - logging in using static token
2024-06-22 14:51:45,912 - __main__ - ERROR - Attempt 5: An error occurred during bot setup or execution: Session is closed
2024-06-22 14:51:45,912 - __main__ - ERROR - Max retries reached, failed to start the Discord bot.
2024-06-22 14:51:46,086 - __main__ - CRITICAL - Unable to start the Discord bot after multiple retries.
Traceback (most recent call last):
  File "/home/server/studio/main.py", line 95, in <module>
    start_discord_bot()
  File "/home/server/studio/main.py", line 80, in start_discord_bot
    bot.run(os.getenv('DISCORD_TOKEN'))
  File "/usr/lib/python3/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/usr/lib/python3/dist-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/usr/lib/python3/dist-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 400, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
2024-06-22 15:01:59,728 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-06-22 15:01:59,732 - discord.client - INFO - logging in using static token
2024-06-22 15:02:01,305 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: d8abe61810aacc1e28ca113fa3ffaa12).
